# Generated by Django 2.2.6 on 2020-06-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
